### ISSUE TITLE
Ubuntu Grub configuration

### ISSUE THREAD

**Issue by AndreaRZ** [antonio-petricca/buddy-linux#3]
Seems there is a difference in location of grub configuration files between Ubuntu and Mint distribution. With Ubuntu distros this prevent the correct execution of the installation script indeed.

**Comment by antonio-petricca** [comment]
The difference was that on Ubuntu **/etc/default/grub.d** did not exist, so I added its conditional creation and released the new version **1.1.4**.

Thank you for your contribution!
